#[derive(Clone, Debug, PartialEq)]
pub enum Token<'a> {
    Directive(&'a str),
    Identifier(&'a str),
    Number(&'a str),
    String(&'a str),
    Element(&'a str),
    LabelHeader(&'a str),
    JumpAddress(&'a str),
    MemoryAddress(&'a str),
    Comma,
    AssignmentOperator,
    Newline,
    OpenBracket,
    CloseBracket,
    Quote,
    OpenBrace,
    CloseBrace,
    OpenParen,
    CloseParen,
    EndOfFile,
    Error { message: String, line_and_column: (usize, usize), snippet: &'a str } ,
}