#[derive(Clone, Debug, PartialEq)]
pub enum Token<'a> {
    Directive(&'a str),
    Identifier(&'a str),
    Number(&'a str),
    String(&'a str),
    LabelHeader(&'a str),
    LabelAddress(&'a str),
    Comma,
    AssignmentOperator,
    Newline,
    OpenBracket,
    CloseBracket,
    Quote,
    OpenBrace,
    CloseBrace,
    OpenParen,
    CloseParen,
    EndOfFile,
    Error { message: String, line: usize, column: usize, snippet: &'a str } ,
}