#[derive(Clone, Debug, PartialEq)]
pub enum Token<'a> {
    Directive(&'a str),
    Identifier(&'a str),
    BinaryNumber(&'a str),
    OctalNumber(&'a str),
    DecimalNumber(&'a str),
    HexNumber(&'a str),
    String(&'a str),
    Element(&'a str),
    LabelHeader(&'a str),
    JumpLabel(&'a str),
    DirectAddress(&'a str),
    IndirectAddress(&'a str),
    Comment(&'a str),
    Comma,
    Newline,
    OpenBracket,
    CloseBracket,
    Quote,
    OpenBrace,
    CloseBrace,
    OpenParen,
    CloseParen,
    EndOfFile,
    Error { message: String, line_and_column: (usize, usize), snippet: &'a str } ,
}
